### ISSUE TITLE
Beta Release TODO Items Tracker

### ISSUE THREAD

**Issue by bearzx** [facebookresearch/torcharrow#362]
Creating a TODO list as we are approaching a beta release, feel free to edit or append items in your comments.

# Repo
- [ ] Move the torcharrow repo to pytorch

# Documentation
- [ ] Change README.md to reflect it's beta release 
- [ ] Fix whatever missing documents we have. @wenleix Feel free to add more detailed items.
  * [ ] `torcharrow.istring_column.StringMethods` substitution: https://github.com/facebookresearch/torcharrow/pull/343#discussion_r879928519

# Packaging
- [ ] Refactor the wheel workflow to make it support both nightly build (automatic run) and release build (manually run)
- [ ] (Optional) Fix velox dylib loading paths for conda build
  - [ ] macos
  - [ ] linux
